name: devops

services:
  # Gitea Database
  gitea-db:
    image: postgres:15-alpine
    container_name: gitea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: giteaUser
      POSTGRES_PASSWORD: ${GITEA_DB_PASSWORD:-YourGitteaPasswordHere}
      POSTGRES_DB: giteaDB
    volumes:
      - ./gitea/postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network
    labels:
      - "homelab.category=devops"
      - "homelab.service=database"
      - "homelab.description=Gitea Database"

  # Gitea Service
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD:-YourGitteaPasswordHere}
      - GITEA__server__DOMAIN=${DOMAIN:-localhost}
      - GITEA__server__SSH_DOMAIN=${DOMAIN:-localhost}
      - GITEA__server__ROOT_URL=http://${DOMAIN:-localhost}/  # Your Domain and your local here **Please update to your desire domain name
    ports:
      - "2222:22"     # SSH access
      - "3000:3000"   # Web interface (external only)
    expose:
      - "3000"        # Web interface (internal only)
    volumes:
      - ./gitea/data:/data
      - ./gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-db
    networks:
      - shared-network
    labels:
      - "homelab.category=devops"
      - "homelab.service=git"
      - "homelab.description=Git Repository Manager"
      - "homelab.url=http://${DOMAIN:-localhost}" # Your Domain and your local here **Please update to your desire domain name

  # Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "50000:50000"  # Agent communication
      - "8080:8080"    # Web interface (external only)
    expose:
      - "8080"         # Web interface (internal only)
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared-network
    labels:
      - "homelab.category=devops"
      - "homelab.service=ci-cd"
      - "homelab.description=Continuous Integration & Deployment"
      - "homelab.url=http://${DOMAIN:-localhost}" # Your Domain and your local here **Please update to your desire domain name

networks:
  shared-network:
    name: shared-network
    external: true